"""Shared workspace configuration, artifact contracts, and Colab utilities.

Canonical source: amazingfly/media-pipeline. Component copies are generated by
scripts/sync_workspace.py; do not edit generated copies.
"""
__version__ = '1.0.0'
